apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: onland-app-test
  name: onland-app-test
  namespace: onland-csp-dev-2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: onland-app-test
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: onland-app-test
        deploymentconfig: onland-app-test
    spec:
      containers:
        - env:
            - name: CSP_LDAP_DN
              value: 'cn=DEV,ou=CSP,ou=private-ldap,dc=teranet-private,dc=ca'
            - name: CSP_BT_DN
              value: >-
                uid=csp_bt_super_user,cn=DEV,ou=CSP,ou=private-ldap,dc=teranet-private,dc=ca
            - name: onland_csp_openldap_lookup_password
              valueFrom:
                secretKeyRef:
                  name: onland-csp-openldap-lookup-password
                  key: onland_csp_openldap_lookup_password
            - name: CSP_DB_URL1
              value: >-
                jdbc:oracle:thin:@//mssctsdbuxdv02.corp.teranet.ca:3031/CSP01DPDB
            - name: CSP_DB_URL2
              value: >-
                jdbc:oracle:thin:@//mssctsdbuxdv02.corp.teranet.ca:3031/CSP01DPDB
            - name: CSP_DB_USER
              value: CSP_ONL2_APP
            - name: CSP_DB_DN
              value: CSP_ONL_APP
            - name: PASSWORD_CONF
              value: /apps/foundation/csp_onl/ldap/config/password.conf
            - name: JAVA_OPTS_APPEND
              value: >-
                -DpropertiesBaseFile=/apps/csp/config/csp-bt.properties
                -DpropertiesErrorMessageFile=/apps/csp/config/bt/validation-bt.properties
                -DlogFilePropertyPath=/opt/eap/standalone/configuration
                -Dlog4j.configurationFile=/opt/eap/standalone/configuration/log4j2-csp-bt.xml
                -Dmdb.user.pwd=password
                -Dunity.properties.location=/apps/foundation/csp_onl/unity/conf
                -Djava.locale.providers=COMPAT
                -DpropertiesTestFile=/opt/eap/standalone/configuration/sample.properties
                -Dorg.jboss.byteman.transform.all=true
                -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager
                -javaagent:/opt/eap/standalone/configuration/byteman/byteman.jar=script:/opt/eap/standalone/configuration/byteman/02901492.btm,sys:/opt/eap/standalone/configuration/byteman/byteman.jar
            - name: EAP_HOME
              value: /opt/eap
            - name: EJB_HOST
              value: onland-bt-app-onland-csp-dev-2.apps.mssocp4uat.corp.teranet.ca
            - name: EJB_USER
              value: csp_bt_super_user
            - name: SCRIPT_DEBUG
              value: "false"
            - name: JBOSS_VERSION
              value: 7.3.6
            - name: DISABLE_EMBEDDED_JMS_BROKER
              value: "true"
          image: >-
            onland-csp-docker-snapshot.artifactory.corp.teranet.ca/onland-test:v1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          name: onland-app
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 35
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /apps/foundation/csp_onl/unity/conf/
              name: volume-unity-config
            - mountPath: /apps/csp/config/
              name: volume-csp-bt-properties
            - mountPath: /apps/csp/config/bt/
              name: volume-validation-bt-properties
            - mountPath: /apps/foundation/csp_onl/ldap/config/
              name: volume-ldap-config
            - mountPath: /apps/foundation/csp/security/
              name: volume-cspstore
            - mountPath: /apps/csp/config/log
              name: volume-log
            - mountPath: /var/log/csp_onl/cspCache
              name: volume-download
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: csp-snap-build
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: csp-pt
          name: volume-csp-pt-properties
        - configMap:
            defaultMode: 420
            name: validation-bt
          name: volume-validation-bt-properties
        - name: volume-ldap-config
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: password
              - configMap:
                  name: dnlist
        - name: volume-unity-config
          projected:
            sources:
              - configMap:
                  name: cart-bt
              - configMap:
                  name: unity-bt
              - configMap:
                  name: unity-auth-bt
            defaultMode: 420
        - name: volume-csp-bt-properties
          configMap:
            name: csp-bt
            defaultMode: 420
        - name: volume-cspstore
          secret:
            secretName: cspstore
            defaultMode: 420
        - emptyDir: {}
          name: volume-log
        - emptyDir: {}
          name: volume-download
  test: false
  triggers: []
